/**
 * The shape of the Kotlin module, as seen from JavaScript.
 *
 * Mirrors
 * `android/src/main/java/expo/modules/ondevicellmandroid/OnDeviceLlmAndroidModule.kt`
 * method for method, argument for argument, and — deliberately — keeps the wire
 * *conventions* of the main package's Apple native types: failures are returned
 * as a discriminated union rather than thrown, and every streaming payload
 * carries its `requestId` so the one shared `onStreamEvent` channel can be
 * demultiplexed (docs/research/android-genai.md §9 — "D17's wire shape …
 * transfers to Android unchanged"). The wire *surface* is this package's own and
 * no longer has to match Apple's argument lists (DECISIONS.md D6).
 *
 * Nothing here imports anything, so the file is safe to load on any platform.
 *
 * Three deltas from the main package's Apple native types, all sourced from
 * docs/research/android-genai.md:
 *
 * 1. **No tool protocol at all.** The ML Kit GenAI Prompt API has no
 *    `Tool`/`FunctionDeclaration` types (§3), so there is no
 *    `NativeToolDefinition`, no `resolveToolCall`, and `AndroidNativeStreamEvent` has
 *    no `toolCall` case.
 * 2. **No structured output.** `GenerateTypedContentRequest` requires a
 *    compile-time Kotlin `KClass` generated by a KSP plugin, so a runtime
 *    JSON Schema handed across the bridge from JavaScript cannot be honoured
 *    (§3). `AndroidNativeResult` has no `objectJson`, and `AndroidNativeStreamEvent` has no
 *    `objectSnapshot` case.
 * 3. **No locale surface.** There is no enumeration API and no
 *    `supportsLocale`-equivalent check (§4) — `capabilities().locales` is
 *    always `UNKNOWN`, so `AndroidNativeCapabilities` carries no `locales` field and
 *    there is no `supportsLocale` method here.
 *
 * One property `the main package's src/apple`'s stream needed that Android's does not: a
 * `reset` flag on `delta`. `generateContentStream` emits true incremental
 * deltas (confirmed from the bytecode, docs/research/android-genai.md §2 —
 * "There is no `StringBuilder`, no `append`, and no accumulator field"), so
 * there is no DECISIONS.md D18-style snapshot-diff fallback to signal.
 */

/**
 * `FeatureStatus`, flattened onto our three usable reasons
 * (docs/research/android-genai.md §5). `reason` is one of
 * `'deviceNotEligible' | 'modelNotReady' | 'unsupportedPlatform'` — already
 * renamed to our vocabulary by the Kotlin side. `'notEnabled'` has no Android
 * analogue (AICore has no user-facing opt-in toggle the way Apple Intelligence
 * does) and the Kotlin side never sends it, but the field stays typed as the
 * full `UnavailableReason` union for forward compatibility.
 */
export interface AndroidNativeAvailability {
  readonly available: boolean;
  readonly reason?: string;
  readonly detail?: string;
}

/** What the model can report about itself. */
export interface AndroidNativeCapabilities {
  /**
   * `GenerativeModel.getTokenLimit()`, already guarded: the native side sends
   * `0` rather than a negative or nonsense value, and `0` means "unknown"
   * (mirrors DECISIONS.md D9). Combined input+output budget, exactly like
   * Apple's `contextSize` (docs/research/android-genai.md §4).
   */
  readonly contextWindow: number;
  /** `GenerativeModel.getBaseModelName()`, e.g. `'nano-v3'`. */
  readonly modelLabel?: string;
}

/** Token usage, shaped like `core`'s `TokenUsage`. */
export interface AndroidNativeUsage {
  readonly inputTokens?: number;
  readonly outputTokens?: number;
  readonly cachedInputTokens?: number;
  readonly reasoningTokens?: number;
}

/** A finished generation. `providerId` is added by the TypeScript side. */
export interface AndroidNativeResult {
  readonly text: string;
  /** A `core` `FinishReason` string. */
  readonly finishReason: string;
  readonly usage?: AndroidNativeUsage;
}

/**
 * A failure already mapped onto an `LLMErrorCode` by the Kotlin side's
 * `GenAiException.ErrorCode` table (docs/research/android-genai.md §5 — 21
 * codes, mapped). Every optional field belongs to exactly one
 * `LLMErrorDetails` variant, exactly as `the main package's src/apple`'s payload does.
 */
export interface AndroidNativeErrorPayload {
  /** An `LLMErrorCode`. Anything unrecognised is treated as `unknown`. */
  readonly code: string;
  readonly message: string;
  /** `unavailable` only. */
  readonly reason?: string;
  /** `contextOverflow` only. From `ErrorCode.REQUEST_TOO_LARGE` / `STRUCTURED_OUTPUT_MAX_TOKENS_ERROR`. */
  readonly contextSize?: number;
  /** `contextOverflow` only. */
  readonly tokenCount?: number;
  /**
   * `unsupportedLocale` only. Unreachable today — there is no locale surface
   * on Android at all (docs/research/android-genai.md §4) — but kept for wire
   * parity with `the main package's src/apple`'s payload in case a future SDK version adds one.
   */
  readonly locale?: string;
  /** `rateLimited` only — milliseconds since the epoch, derived from `GenAiException.getRetryDelay()`. */
  readonly resetDate?: number;
  /** `unknown` only — the router hint. */
  readonly transient?: boolean;
  /** Diagnostics for the untyped/`UNKNOWN` branch. */
  readonly nativeDomain?: string;
  readonly nativeCode?: number;
  readonly nativeDetail?: string;
}

/** What `generate` resolves to. */
export type AndroidNativeGenerateOutcome =
  | { readonly ok: true; readonly result: AndroidNativeResult }
  | { readonly ok: false; readonly error: AndroidNativeErrorPayload };

/** What `countTokens` resolves to. */
export type AndroidNativeCountTokensOutcome =
  | { readonly ok: true; readonly count: number }
  | { readonly ok: false; readonly error: AndroidNativeErrorPayload };

/**
 * One `onStreamEvent` payload. Exactly one terminal event per request. No
 * `objectSnapshot` or `toolCall` cases — see the file docblock.
 */
export type AndroidNativeStreamEvent =
  | { readonly requestId: string; readonly type: 'delta'; readonly delta: string }
  | { readonly requestId: string; readonly type: 'finish'; readonly result: AndroidNativeResult }
  | {
      readonly requestId: string;
      readonly type: 'error';
      readonly error: AndroidNativeErrorPayload;
    };

/** What Expo's `addListener` hands back. */
export interface AndroidNativeSubscription {
  remove(): void;
}

/**
 * The Kotlin module's exported surface.
 *
 * Registered as **`OnDeviceLlmAndroid`** — see `expo-module.config.json` and
 * `Name("OnDeviceLlmAndroid")` in the Kotlin module. The rename away from the
 * main package's `OnDeviceLlm` is DECISIONS.md D1 at the wire: one registered
 * name now has exactly one native implementation, so `./resolve.ts` no longer
 * has to work out which platform's module Expo handed it.
 *
 * `supportsLocale` and the `schemaJson` / `tools` / `toolCallTimeoutMs`
 * arguments are absent, by D6 — they existed only so one TypeScript caller could
 * drive both platforms' modules under one name, and the wave-1 arity mismatch
 * they caused (Kotlin `generate` declared five positional arguments, this
 * interface described four) is the sort of defect a shim nobody calls invites.
 */
export interface AndroidNativeModule {
  availability(): Promise<AndroidNativeAvailability>;
  capabilities(): Promise<AndroidNativeCapabilities>;
  generate(
    requestId: string,
    messages: readonly { readonly role: string; readonly content: string }[],
    temperature: number | null,
    maxOutputTokens: number | null
  ): Promise<AndroidNativeGenerateOutcome>;
  /**
   * Starts a stream and resolves as soon as it is registered — *not* when
   * generation finishes. Results, errors and cancellation all arrive as
   * `onStreamEvent` events.
   */
  startStream(
    requestId: string,
    messages: readonly { readonly role: string; readonly content: string }[],
    temperature: number | null,
    maxOutputTokens: number | null
  ): Promise<void>;
  /**
   * Cancels the underlying coroutine. Resolves `false` when the id is already
   * gone.
   *
   * Whether cancelling actually stops AICore inference, rather than merely
   * stopping event delivery, is unverified without hardware
   * (docs/research/android-genai.md §2, §11 item 7) — flagged for the wave-2
   * spike, not something this TypeScript layer can settle.
   */
  cancel(requestId: string): Promise<boolean>;
  /** Hint that a request is coming (`GenerativeModel.warmup()`). Resolves `false` if the hint could not be delivered. */
  prewarm?(
    messages: readonly { readonly role: string; readonly content: string }[] | null
  ): Promise<boolean>;
  /** Exact token count for these messages, via `GenerativeModel.countTokens(request)`. */
  countTokens?(
    messages: readonly { readonly role: string; readonly content: string }[]
  ): Promise<AndroidNativeCountTokensOutcome>;
  addListener(
    eventName: 'onStreamEvent',
    listener: (event: AndroidNativeStreamEvent) => void
  ): AndroidNativeSubscription;
}
