/**
 * Conversions between the native wire shapes and `core`'s types, plus the
 * request validation that happens *before* anything crosses the bridge.
 *
 * Same rationale as `the main package's src/apple/wire.ts` (the main package's docs/plan.md §1, "when a design
 * choice trades native code for TypeScript, prefer TypeScript"): the rules
 * are unit-testable in Node, a rejected request costs no bridge hop, and the
 * message can be as specific as it needs to be.
 *
 * Two rejections below have no Apple equivalent and exist only here:
 * `schema` and `tools` are turned away unconditionally, because
 * `capabilities()` always reports `structuredOutput: false` and
 * `tools: false` for this provider (docs/research/android-genai.md §3 — no
 * tool types exist anywhere in the SDK, and structured output requires a
 * compile-time Kotlin class a runtime JSON Schema cannot produce). This is
 * the same guard `the main package's src/openai/provider.ts`'s `rejectTools` ships, just applied
 * to both fields and hoisted into the request builder so `generate` and
 * `stream` share one check.
 */

import {
  LLMError,
  type FinishReason,
  type GenerateRequest,
  type Message,
  type TokenUsage,
} from '@taaltreelabs/on-device-llm/core';

import type { AndroidNativeUsage } from './native/types';

const FINISH_REASONS: readonly FinishReason[] = [
  'stop',
  'length',
  'guardrail',
  'refusal',
  'cancelled',
  'toolCalls',
  'other',
];

/** A native finish-reason string, validated. Anything unrecognised is `'other'`. */
export function toFinishReason(value: string | undefined): FinishReason {
  return FINISH_REASONS.includes(value as FinishReason) ? (value as FinishReason) : 'other';
}

/** Native usage -> `TokenUsage`, or `undefined` when nothing was reported. */
export function toTokenUsage(usage: AndroidNativeUsage | undefined): TokenUsage | undefined {
  if (usage === undefined) return undefined;
  const mapped: TokenUsage = {
    ...(typeof usage.inputTokens === 'number' ? { inputTokens: usage.inputTokens } : {}),
    ...(typeof usage.outputTokens === 'number' ? { outputTokens: usage.outputTokens } : {}),
    ...(typeof usage.cachedInputTokens === 'number'
      ? { cachedInputTokens: usage.cachedInputTokens }
      : {}),
    ...(typeof usage.reasoningTokens === 'number'
      ? { reasoningTokens: usage.reasoningTokens }
      : {}),
  };
  return Object.keys(mapped).length > 0 ? mapped : undefined;
}

function invalid(message: string, providerId: string): LLMError {
  return new LLMError({ code: 'invalidRequest' }, { message, providerId });
}

/**
 * Reject a request carrying `schema` up front.
 *
 * `capabilities().structuredOutput` is always `false` for this provider: the
 * Prompt API's typed path (`GenerateTypedContentRequest<T>`) terminates in a
 * `KClass` produced by a KSP compiler plugin at build time, and there is no
 * public API that accepts a runtime JSON Schema document
 * (docs/research/android-genai.md §3). Rejecting here means the developer
 * hears about it at the call site instead of the model quietly answering in
 * prose.
 */
function rejectSchema(request: GenerateRequest, providerId: string): void {
  if (request.schema === undefined) return;
  throw invalid(
    'This provider does not support structured output (`capabilities().structuredOutput` is ' +
      "false). The ML Kit GenAI Prompt API's typed output only accepts a compile-time Kotlin " +
      'class generated by a KSP plugin, so a runtime JSON Schema handed across the bridge from ' +
      'JavaScript cannot be honoured (docs/research/android-genai.md §3). Remove `schema`, or ' +
      'route the request to a provider that reports `structuredOutput: true`.',
    providerId
  );
}

/**
 * Reject a request carrying `tools` up front.
 *
 * `capabilities().tools` is always `false` for this provider: no
 * `Tool`/`FunctionDeclaration`/`FunctionCall` type exists anywhere in
 * `genai-prompt` or `genai-common` (docs/research/android-genai.md §3).
 * Answering anyway would let a model that was supposed to look something up
 * invent it instead, which is the one outcome worse than an error — the same
 * reasoning `the main package's src/openai/provider.ts`'s `rejectTools` documents.
 */
function rejectTools(request: GenerateRequest, providerId: string): void {
  if (request.tools === undefined || request.tools.length === 0) return;
  throw invalid(
    'This provider does not support tool calling (`capabilities().tools` is false). The ML Kit ' +
      'GenAI Prompt API has no tool-calling surface at all (docs/research/android-genai.md §3). ' +
      'Remove `tools`, or route the request to a provider that reports `tools: true`.',
    providerId
  );
}

/** The validated, bridge-ready form of a request. */
export interface NativeRequestArgs {
  readonly messages: { readonly role: string; readonly content: string }[];
  readonly temperature: number | null;
  readonly maxOutputTokens: number | null;
}

/**
 * Validate a `GenerateRequest` and flatten it for the bridge.
 *
 * Rejections, and why each one is `invalidRequest` (never retried, never
 * failed over — it will fail the same way next time):
 *
 * - **`schema`** and **`tools`**: see {@link rejectSchema} and
 *   {@link rejectTools} above.
 * - **empty `messages`**: there is nothing to respond to.
 * - **a conversation with only `system` messages**: same reason.
 * - **a non-finite `temperature`** or a **non-positive, non-integer
 *   `maxOutputTokens`**: the native side would take them and misbehave later,
 *   further from the cause.
 *
 * Deliberately *not* checked here, unlike `the main package's src/apple/wire.ts`'s D17 rule:
 * whether the conversation must end with a `user` message. The Prompt API's
 * `Content` has no role field at all — multi-turn attribution is an encoding
 * this provider's Kotlin half has to invent, and it is unverified without
 * hardware (docs/research/android-genai.md §1, §10 — "the worst gap"). Adding
 * a same-as-Apple structural rule here would assert a turn-taking discipline
 * this provider cannot yet honour on the wire; that decision belongs to the
 * wave-2 hardware spike once the role encoding is settled, not to this file.
 */
export function buildNativeRequest(
  request: GenerateRequest,
  providerId: string
): NativeRequestArgs {
  rejectSchema(request, providerId);
  rejectTools(request, providerId);

  const messages = request.messages;
  if (messages.length === 0) {
    throw invalid('`messages` is empty; there is nothing to respond to.', providerId);
  }

  const turns = messages.filter((message: Message) => message.role !== 'system');
  if (turns.length === 0) {
    throw invalid(
      'The request contains only system messages; the Android provider needs a user message to ' +
        'respond to.',
      providerId
    );
  }

  if (request.temperature !== undefined && !Number.isFinite(request.temperature)) {
    throw invalid(
      `\`temperature\` must be a finite number, got ${request.temperature}.`,
      providerId
    );
  }
  if (
    request.maxOutputTokens !== undefined &&
    (!Number.isInteger(request.maxOutputTokens) || request.maxOutputTokens <= 0)
  ) {
    throw invalid(
      `\`maxOutputTokens\` must be a positive integer, got ${request.maxOutputTokens}.`,
      providerId
    );
  }

  return {
    messages: messages.map((message) => ({ role: message.role, content: message.content })),
    temperature: request.temperature ?? null,
    maxOutputTokens: request.maxOutputTokens ?? null,
  };
}

let requestCounter = 0;

/**
 * A request id unique within this JS context. See `the main package's src/apple/wire.ts`'s
 * `nextRequestId` for why this is a counter rather than a UUID; only the
 * prefix differs, so ids from the two providers are distinguishable in logs.
 */
export function nextRequestId(): string {
  requestCounter += 1;
  const random = Math.random().toString(36).slice(2, 8);
  return `android-${Date.now().toString(36)}-${requestCounter}-${random}`;
}
